# Changes here will be overwritten by Copier
_commit: 51ca397
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
email: dev@1kbgz.com
github: 1kbgz
project_description: lerna is a collection of plugins and extensions for hydra
project_name: lerna
python_version_primary: '3.11'
team: the lerna authors
